export const jadval = [
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Dushanba",
    teacher: "Ismoilov Rahmon",
    subject: "Adabiyot",
    number: "1",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Dushanba",
    teacher: "Ismoilov Rahmon",
    subject: "Ona tili",
    number: "2",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Dushanba",
    teacher: "Ismoilov Rahmon",
    subject: "Matematika",
    number: "3",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Dushanba",
    teacher: "Ismoilov Rahmon",
    subject: "Rus tili",
    number: "4",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Seshanba",
    teacher: "Ismoilov Rahmon",
    subject: "Adabiyot",
    number: "1",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Seshanba",
    teacher: "Ismoilov Rahmon",
    subject: "Ona tili",
    number: "2",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Seshanba",
    teacher: "Ismoilov Rahmon",
    subject: "Matematika",
    number: "3",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Seshanba",
    teacher: "Ismoilov Rahmon",
    subject: "Rus tili",
    number: "4",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Chorshanba",
    teacher: "Ismoilov Rahmon",
    subject: "Adabiyot",
    number: "1",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Chorshanba",
    teacher: "Ismoilov Rahmon",
    subject: "Ona tili",
    number: "2",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Chorshanba",
    teacher: "Ismoilov Rahmon",
    subject: "Matematika",
    number: "3",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Chorshanba",
    teacher: "Ismoilov Rahmon",
    subject: "Rus tili",
    number: "4",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Payshanba",
    teacher: "Ismoilov Rahmon",
    subject: "Adabiyot",
    number: "1",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Payshanba",
    teacher: "Ismoilov Rahmon",
    subject: "Ona tili",
    number: "2",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Payshanba",
    teacher: "Ismoilov Rahmon",
    subject: "Matematika",
    number: "3",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Payshanba",
    teacher: "Ismoilov Rahmon",
    subject: "Rus tili",
    number: "4",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Juma",
    teacher: "Ismoilov Rahmon",
    subject: "Adabiyot",
    number: "1",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Juma",
    teacher: "Ismoilov Rahmon",
    subject: "Ona tili",
    number: "2",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Juma",
    teacher: "Ismoilov Rahmon",
    subject: "Matematika",
    number: "3",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Juma",
    teacher: "Ismoilov Rahmon",
    subject: "Rus tili",
    number: "4",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Shanba",
    teacher: "Ismoilov Rahmon",
    subject: "Adabiyot",
    number: "1",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Shanba",
    teacher: "Ismoilov Rahmon",
    subject: "Ona tili",
    number: "2",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Shanba",
    teacher: "Ismoilov Rahmon",
    subject: "Matematika",
    number: "3",
  },
  {
    class_number: 11,
    class_char: "A",
    smena: 1,
    day: "Shanba",
    teacher: "Ismoilov Rahmon",
    subject: "Rus tili",
    number: "4",
  },
];
